### ISSUE TITLE
Unexpected backslash processing during variable expansion

### ISSUE THREAD

**Issue by j4james** [catseye/Falderal#2]
I've been trying to get Falderal working on Windows, but I found my target interpreter wasn't able to open the test source, because the path in the `%(test-body-file)` parameter was corrupted (the backslashes in the path were being "expanded", e.g. the `\t` in `c:\tmp` would be interpreted as a tab).

Now I realise that Windows may not be a platform you want to support, but this looks like it's a general problem for all of the variable expansion, and could affect other platforms. For example, if you were using the `%(test-body-text)` variable to pass the source code as text, then a backslash there could also be mistakenly processed.

The problem is the use of `re.sub` for the variable replacement, since that does backslash processing on the replacement string. You can easily fix this just by replacing those calls with the `string.replace` method instead (there is no need for regex in any of these cases).

In case it helps, this is a patch of the fix I've been using: [variable-expansion-patch.txt](https://github.com/catseye/Falderal/files/2421173/variable-expansion-patch.txt)

**Comment by cpressey** [comment]
Wow, I did not realize `re.sub` did that to replacement strings (even though [the `re.sub` docs say so in the 2nd sentence](https://docs.python.org/3.5/library/re.html#re.sub).)  That is definitely a bug and, yes, since the power of `re` is not needed here, `string.replace` should be perfectly adequate and thus preferred.  I'll work on getting your patch in and releasing another minor version.  Thanks!

**Comment by cpressey** [comment]
Have started a [development branch for version 0.12](https://github.com/catseye/Falderal/compare/develop-0.12).  I don't know when this will be actually released (I'd like to support Python 3 in the next release), but for now, it can at least be used.

**Comment by j4james** [comment]
Thanks. No rush on the release. I'm just experimenting at the moment, and there were one or two other issues I wanted to raise (still trying to put together a patch). Btw I'm really enjoying using this - it's a cool concept.

**Comment by cpressey** [comment]
Thanks! Glad you're enjoying this humble constituent of Cat's Eye Technologies' Vast NIH Archipelago. I'll try to work on it the next few days, and hopefully get it to a state where the next release can be made.
