### ISSUE TITLE
Falderal can't easily test the Befunge reference implementation

### ISSUE THREAD

**Issue by j4james** [catseye/Falderal#4]
I was trying to use _Falderal_ to create some Befunge tests and run them against the Befunge reference implementation, _bef_. However all the tests failed with an error message something like:

    Error: couldn't open 'tmpug9hwq.bf' for input.

It turns out the problem was that _Falderal_ was saving the output in a temporary file with no extension (e.g. something like _tmpug9hwq_), but when _bef_ is given a filename with no extension it automatically appends _.bf_ and thus fails to find the file.

So I was wondering whether it might be a good idea for _Falderal_ to have an option when setting up the implementation to specify an extension to use for source files, e.g. 

    Functionality X is implemented by shell command Y with extension Z

But maybe that's an overcomplication for something that isn't really _Falderal_'s problem - it might easier, and more reasonable, to have _bef_ fix the issue. For example you could make _bef_ check if the provided source file exists, and only try append a _.bf_ extension if it can't be found with the original name.

Anyway, if you think it's _bef_'s problem, you can just close this and I can re-raise this issue there (I'd be happy to put together a patch if that'll help).

Or if you think it's too much of an edge case for either app to deal with, I can accept that too - it's not that big a deal to work around, since I'm already using a kind of proxy launcher to redirect the calls to the different implementations I want to test.

**Comment by cpressey** [comment]
The following might work:

    Functionality X is implemented by shell command
    "cp %(test-body-file) %(test-body-file).bf && bef %(test-body-file).bf && rm %(test-body-file).bf"

(Having used Falderal extensively at this point, I'm used to coming up with shell workarounds to deal with strange cases, and I tend not to even think of them as workarounds, but just "how it's done", which is possibly sad, but possibly not as it's kind of an extension of shell programming where you just do this sort of thing all the time.)

That *should* work, actually, so if it doesn't, that's a bug.

One shortcoming is that if it fails, it leaves a `.bf` file in the `/tmp/` directory.  That's not a bug but it would be nice if there was a way to clean those up.  Maybe making a temp subdir, and then deleting that entire subdir at the end, or something.

**Comment by j4james** [comment]
The more I think about, the more I think that's a perfectly reasonable approach to take. For my particular use case, I'd probably still handle the workaround elsewhere, but the fact that it can be done within the Falderal implementation spec is enough to convince me that you don't need anything more than that. Feel free to close this issue.

**Comment by cpressey** [comment]
"Glue code" is the phrase that wasn't occurring to me, but should've been, when I wrote that. For better or worse, writing glue code to test a particular functionality in Falderal is standard practice.

I also totally forgot (sorry!) when I wrote that response that you are most likely using Windows, and while I'm sure you can write some kind of glue to make this work on Windows, that same glue likely won't work on Unix, and I acknowledge that is one of the drawbacks to the approach.

Also, `bef`'s behaviour in this regard *is* silly and smacks of bygone MS-DOS days, but that's a separate issue, which you can bring up in the Befunge-93 issues section if you like.
